default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: rs_blackmarket_api_development

test:
  <<: *default
  database: rs_blackmarket_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
